### ISSUE TITLE
Not compatable with Debian 10

### ISSUE THREAD

**Issue by m-eddington** [mumble-voip/mumo#15]
I recently upgrade my Debian 9 server to Debian 10, but mumo (or rather, some of the plugins) doesn't seem to work all that well.

- The onjoin-module only seems to work sometimes, I've tested from multiple Operating Systems and Mumble clients (stable and development). ~~I Need to try from a clean install to figure out if it's something cached in the clients or if it's simply not working at all.~~ Confirmed - not working in a clean Debian 10 install with mumble from Debian repos.
- The idelmove.ini and antirec.ini doesn't work at all.

So I'm thinking it might have something to do regarding any python upgrades, which (would) mean mumo is completely broken in Debian 10. Don't take my word for it though, I can't code at all :) Let me know if you need any log-files or similar.

`# python2.7 mumo.py`

Results in the following log-output:

```
2019-08-17 00:18:44,497 ERROR root Retrieving slice from server failed
2019-08-17 00:18:44,497 ERROR root Slice preprocessing failed for `'
Traceback (most recent call last):
  File "mumo.py", line 115, in dynload_slice
    load_slice(dynslicefilepath)
  File "mumo.py", line 90, in load_slice
    Ice.loadSlice('', slicedirs + [slice])
RuntimeError: Slice preprocessing failed for `'
Traceback (most recent call last):
  File "mumo.py", line 562, in <module>
    ret = do_main_program()
  File "mumo.py", line 152, in do_main_program
    dynload_slice(prx)
  File "mumo.py", line 115, in dynload_slice
    load_slice(dynslicefilepath)
  File "mumo.py", line 90, in load_slice
    Ice.loadSlice('', slicedirs + [slice])
RuntimeError: Slice preprocessing failed for `'
```

**Comment by wrapper** [comment]
I get the same error on Ubuntu 18, any solutions? Thanks

**Comment by Kissaki** [comment]
What server did you install? Where did you get it from? Does it have Ice enabled?
