### ISSUE TITLE
Is it possible to update mumo to python 3?

### ISSUE THREAD

**Issue by deluxghost** [mumble-voip/mumo#18]
I know mumo just works fine, but Python 2 is going to die very soon.

And another thing, it's really annoying to write non-ascii strings in Python 2 (either `u'string'` or import future)

I have tried to update it myself but turns out that is too complicated for me.

**Comment by AnonFuncsAreAwesome** [comment]
I have updated mumo to python3 some years back, maybe we can get it upstreamed here. I need to rebase it against master and clean up commits, that can take a while.

https://git.harting.dev/anonfunc/mumo3

**Comment by Kissaki** [comment]
That would be great

**Comment by AnonFuncsAreAwesome** [comment]
See #21.
