### ISSUE TITLE
Is mumo still alive?

### ISSUE THREAD

**Issue by elandorr** [mumble-voip/mumo#24]
Mainly interested for use with the antirec plugin: https://github.com/Natenom/mumblemoderator-module-collection. Not making abuse THIS easy is a must-have before I can consider using mumble.

(Yes, it can be circumvented, but it's better than having a 1-click-abuse-button.

This unanswered issue suggests it's currently broken entirely. https://github.com/mumble-voip/mumo/issues/23
The fix seems trivial, but what's the point of starting to use something, if it's not actively maintained?

The docker image is severely outdated as well.

**Comment by Kissaki** [comment]
Not sure how to answer this. Whether to use it or not will be a decision you have to make. You laid out what you need to make that decision, no?

If it is a trivial fix, please test and submit it. Then we will do our best for a timely review and integration/merge.

**Comment by Kissaki** [comment]
Nobody is contracted and paid to maintain this, if that is what you are asking. You're better off viewing this project as a community project than a product being sold to you. Community projects live and die with their interested parties; volunteers and users. Demanding a better state of the project while not contributing is… yeah. If you want to see it better, we'd love to see you contribute.

**Comment by elandorr** [comment]
How do you misinterpret this as a demand? I was asking, if this is still alive, so I knew whether or not to bother.

I intensely dislike tech and fully understand, if one abandons yet another maintenance responsibility. I have enough crap to maintain myself, that I don't really care about.

The mumble space is completely abandoned, and I moved on. Naked Mumble is useful enough at the moment and that'll have to do.
