### ISSUE TITLE
protocol error: out of bounds during unmarshaling

### ISSUE THREAD

**Issue by roughnecks** [mumble-voip/mumo#27]
Hello,

```
2024-02-11 20:07:40,563 WARNING Ice dispatch exception: src/Ice/InputStream.cpp:404: ::Ice::UnmarshalOutOfBoundsException:
protocol error: out of bounds during unmarshaling
identity: 0BC87-string
facet:
operation: userTextMessage
remote host: 127.0.0.1 remote port: 42520
```

I'm running mumo from git on a Debian Stable server, with murmur version=1.5.517 and ice packages from upstream repo:

`ii  python3-zeroc-ice                                3.7.10-1`
`ii  zeroc-ice-slice                                  3.7.10-1`

I only loaded the "seen" module and I'm getting errors every time an event (like connection/disconnection) happens.

**Comment by Kissaki** [comment]
I enabled the seen module. I connected and disconnected. Works for me. No errors. Neither in mumo.log nor murmur.log.

* Mumo, current master, on Windows on bash/Ubuntu via WSL
* Mumble Server 1.4.287

What did you quote? Your Mumo or Mumble Server log?

**Comment by roughnecks** [comment]
Hi, think it was mumo.log

I had removed everything until now and when trying again I got it working, so case closed.

Thanks
