### ISSUE TITLE
Cannot run docker container

### ISSUE THREAD

**Issue by roughnecks** [mumble-voip/mumo#37]
https://paste.woodpeckersnest.space/?63cdb956502b10ec#FktKpwgvZuWgjD7G4SYVWbuTFamm9zffoLHSbBHxZYVy

At first I had a "modules" not found error, so I copied that dir from my mumo clone into `/home/debian/docker/etc/mumo/data`
After that looked like solved I tried setting the Murmur.ice file in mumo.ini in several ways, from absolute to relativa paths, but it was always looking for /mumo/Murmur.ini, without founding it
Then I added a volume just for that file and I made progress, but in the end there's always a traceback.

Everything is in the link above, please advice.

Thanks

**Comment by Kissaki** [comment]
Why do you set a slice path in the mumo.ini? Do you not want it to load it from the server?

---

Copying out the relevant:

```
slice = Murmur.ice
icecpp: error: cannot open `/mumo/Murmur.ice' for reading
-v /home/debian/docker/etc/mumo/data:/data
```

You placed the Murmur.ini in the data folder, but did not specify it as such.

I would advise not specifying `slice`. But if you for some reason still want to, configure the correct path

```
slice = /data/Murmur.ice
```

**Comment by Kissaki** [comment]
The second error

```
no argument provided for -h option in endpoint `tcp  -h'
```

The host should come from the ini setting

```
host = 127.0.0.1
port = 6502
```

Dunno how that could go wrong when it's in the ini!?

**Comment by roughnecks** [comment]
If I don't set a murmur.ice file, it doesn't load from server, here's the log:

```
2024-03-16 12:57:59,163 INFO root Loading slice from server...
2024-03-16 12:57:59,168 ERROR root Retrieving slice from server failed
2024-03-16 12:57:59,168 ERROR root Ice.SocketException:
Cannot assign requested address
```

Anyway, some progress: https://paste.woodpeckersnest.space/?cd524ffd2263bf76#5V4Ev6urar49cAExpFtQWX97MBgYMezLnq79GiD5W67y

**Comment by Kissaki** [comment]
> `File "/data/Murmur.ice", line 6446, in addCallback`

I read this as the retrieving slice from server works fine. The error occurs later, when addCallback is called.

What's your network setup between Mumble Server and Mumo?

This seems to me like like a networking issue.

**Comment by roughnecks** [comment]
> I read this as the retrieving slice from server works fine. The error occurs later, when addCallback is called.

No, it works if I specify /data/Murmur.ini in mumo.ini. If I leave "slice =" (empty) as you told me, the error comes up (ERROR root Retrieving slice from server failed) and I wouldn't know how to configure that in mumble-server.ini.

Alright, so I have to use "network host" in docker, otherwise it cannot see murmur on localhost.
Now it's fixed, last thing is making it so it can download the slice from server, if you can help.

Thanks

**Comment by Kissaki** [comment]
If Mumo can connect to Ice I don't see why retrieving the slice would fail.

Have you tried after adding the missing docker network host?

https://github.com/mumble-voip/mumo/blob/master/docker.md

**Comment by roughnecks** [comment]
> Have you tried after adding the missing docker network host?

right, I didn't try. Works now 👍
