### ISSUE TITLE
Daemon Not working correctly 

### ISSUE THREAD

**Issue by lukepolo** [mumble-voip/mumo#6]
:/opt/mumo# pip install python-daemon
Requirement already satisfied (use --upgrade to upgrade): python-daemon in /usr/local/lib/python2.7/dist-packages
Cleaning up...

:/opt/mumo# python mumo.py -d

Fatal error, could not daemonize process due to missing "daemon" library, please install the missing dependency and restart the application
:/opt/mumo# 

Any ideas?

**Comment by Kissaki** [comment]
I’m not that familiar with the python ecosystem. But could it be a v2 vs v3 issue?
pip seems to use python 2. When you call python (as in `python mumo.py -d`), which version is run? 2 or 3?

**Comment by lukepolo** [comment]
Python 2.7.10

**Comment by hacst** [comment]
Try launching python manually and then doing:
```
import daemon
import daemon.pidlockfile
```
One of those should throw an exception that might tell you more about what's up. What distro are you on?

**Comment by lukepolo** [comment]
Sorry about the really late reply, I was gone out of the country. 

```
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import daemon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named daemon
>>> 
```

**Comment by hacst** [comment]
From the python output I'm assuming you are on Mac? Unfortunately I know pretty much nothing about potential quirks python or pip might have on that platform :( 

Purely from the failing import I would guess something went awry with your pip install of python-daemon. The daemon package should be available after installing it (see https://pypi.python.org/pypi/python-daemon/). You might want to try to force pip to reinstall the package to see if that fixes it.

**Comment by lukepolo** [comment]
I'm on
ubuntu 15.10.

**Comment by lukepolo** [comment]
Will try to reinstall

**Comment by hacst** [comment]
Huh? Your output snippet said:
```
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
```
Darwin is the OSX Kernel and Apple LLVM the OSX compiler of choice so I'm kinda confused.

**Comment by lukepolo** [comment]
Im sorry, I must have ran it on my mac instead of my server..


```
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import daemon
>>> import daemon.pidlockfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pidlockfile
>>> 

```

**Comment by hacst** [comment]
Hi. Seems like the daemon library changed in more recent versions. Could you please try the current master and see if it fixes your problem? Thanks.

**Comment by lukepolo** [comment]
Yah will do tonight.
