### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by cap-42** [mumble-voip/mumo#7]
Hi, 
when starting the daemon like so:
`$ python mumo.py -a`
I get this error:
```
  File "mumo.py", line 102
    if IcePy.intVersion() < 30500L:
                                 ^
SyntaxError: invalid syntax
```
I'm not familiar with python. Given that the file has been around like this for months, it's probably an issue with my setup. I'd appreciate any pointers on how to take care of this.
Cheers

**Comment by hamilton5** [comment]
give us some information about your setup... distro even? looks like maybe a custom build in the mix? is your ice and things at or above the correct versions for example?

**Comment by cap-42** [comment]
I'm on archlinux kernel 2.6.32-45 using the ice packages from AUR:
zeroc-ice 3.6.2-2
python-zeroc-ice 3.6.2.1-1
python2-zeroc-ice 3.6.2.1-1
murmur-ice 1.2.16-1
Thanks for looking into this!

**Comment by hamilton5** [comment]
two versions of python might be a problem... can you say what version is running the script ?

**Comment by cap-42** [comment]
Both python-zeroc packages were dependencies of the mumble-ice.
anyway, you were right about python version being the culprit here. python v3.5.2 is linked to the python call, but using python2 fixed the issue.
Thanks for putting me on the right track!
