### ISSUE TITLE
white list specific channels?

### ISSUE THREAD

**Issue by hamilton5** [mumble-voip/mumo#8]
I wanted to be able to white list people in specific channels... 
```python
        # Check if the user or channel is whitelisted
        if user.name in scfg.whitelist:
            return

        if str(user.channel) in scfg.whitelist:
            return
        
        # Remember values so we can see changes later
        channel = user.channel
        threshold = None
        mute = user.mute
```

**Comment by hacst** [comment]
Hi. Your implementation isn't quite correct. For one it mixes usernames and channel ids which could be abused (though admittedly it's more of a correctness issue than a threat). On the other hand it uses the wrong location to prevent the plugin from acting. Where it is now if a user was moved to afk and hence muted & deafened by the plugin he would not get unmuted by leaving afk if he happened to join a whitelist channel.

#9 is my suggestion on how to do it. If you can verify it works (I currently don't have a stuff setup to test mumo properly) I can land it for everyone.

**Comment by hamilton5** [comment]
Very cool, Thanks for taking the time to implement this (correctly) it seems to be working fine.

**Comment by hacst** [comment]
Thanks for testing it. I landed the PR.
